### ISSUE TITLE
Support for Discourse?

### ISSUE THREAD

**Issue by vsoch** [cilogon/service-lib#1]
Hi! I'm a research software engineer at Stanford, and we use your service here and there for our tools. I'm interested in how hard it would be to get CILogon working with a discourse board. For example, here is a plugin / walk through to get SSO working (and it's ruby) :point_right: https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045

This is for the site https://ask.cyberinfrastructure.org/, and it's really important because we have users from institutions across the board, and we want to be able to link them back to their institution and then possibly help with posting permissions (for example, here is the Stanford topic board --> https://ask.cyberinfrastructure.org/c/stanford-research-computing) Thanks so much for your help!

**Comment by terrencegf** [comment]
Hello vsoch, I'm not familiar with Discourse, but looking at their github repo, I think the https://github.com/discourse/discourse-oauth2-basic plugin or https://github.com/discourse/discourse-openid-connect plugin (in development) would satisfy your needs. (I'm not sure of the use-case for the SSO plugin). For info on using the CILogon OAuth2/OIDC service, please see https://www.cilogon.org/oidc .
